### PR TITLE
Control Copy-Paste chromeapp over a tcp socket

### PR DESCRIPTION
**Pull request by mollyling**
Tested on two laptops at home, was able (still copy-pasting, but into TELNET sessions, the goobuntu firewall setup is pretty strict) to proxy www.google.com using curl -x socks5h://localhost:9999 www.google.com

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-networking/255)

### CODE REVIEW

**Comment by trevj** [comment]
Super cool! I love how this can be a key part of our testing setup.

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 63 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5M4hVWPwxFalOhTAT)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L63)):</sup>
Short comment would be good here, e.g.:

``` js
// Alternative way to send and receive commands and signalling messages.
```

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 72 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5MNpe8BJBalRV25YH)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L72)):</sup>
I think we can achieve this without the round-trip to the UI.

Let's replace all calls to `parentModule.emit('signalForPeer', signal) with a call to a new method which does two things:
1. `parentModule.emit('signalForPeer', signal);`
2. sends the signal to any open TCP connections

The second part is what you currently have as `giveSendBack`.

This will also remove the assumption of only one signalling message on each side, which could change in future.

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 76 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5OQQPlVkZD6J1Vrs8)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L76)):</sup>
I wonder if we really need `GIVE`? We could just assume that any input that isn't a command (just `GET` for now, but could expand in the future, e.g. `ENCRYPT`) is a signalling message.

See my next comment for how we can make this work.

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 80 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5PsHGYYAsfMb_5u2S)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L80)):</sup>
Again, we don't need the UI round-trip. Just factor out the `handleSignalMessage` handler, as you did for `doStart`.

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 85 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5PgsXlrig0fAwsIPh)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L85)):</sup>
For Colossal Cave compatibility: `I don't understand that command.`

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 89 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5KNcDv-k9rQu6c3c3)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L89)):</sup>
I think we could remove the `Starting TCP Server` and `Got a TCP connection` lines in favour of logging here (we can also add the listening endpoint), e.g.:

``` typescript
tcpServer.server.listen().then((endpoint) => {
  log.info('command server listening on %1', endpoint);
}).catch((e:Error) => {
  log.error('failed to start comand server: %2', e.message);
});
```

This will also tell us when the command server fails to start, which will happen if you start two instances on the same machine (which I do all the time).

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255)

**Comment by mollyling** [comment]
PTAL, thanks.

**Comment by mollyling** [comment]
<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 63 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5M4hVWPwxFalOhTAT)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L63)):</sup>
Done.

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 72 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5MNpe8BJBalRV25YH)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L72)):</sup>
I tried to, but found that we needed to go to the UI for the encoding into base64.

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 76 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5OQQPlVkZD6J1Vrs8)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L76)):</sup>
I think we could logically remove it, but I hesitate to do so.  I think there are benefits for making the protocol more explicit - easier to debug if needed, easier to extend, and it's easier to understand the script giving the commands.  Was something simplified if we got rid of it?

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 85 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5PgsXlrig0fAwsIPh)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L85)):</sup>
Done.  But I don't know what Colossal Cave is.  

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 89 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5KNcDv-k9rQu6c3c3)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L89)):</sup>
Done, good point.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255)

**Comment by mollyling** [comment]
Ok, I did a few changes (not all), and: 
- Added a runner script to connect two peers
- Try 4 different binding ports on the same host (9000, 9010, 9020, 9030).

**Comment by trevj** [comment]
Awesome. Sorry I didn't see your last response until today.

:+1:

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 79 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5MNpe8BJBalRV25YH)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L79)):</sup>
Ah, damn. We might want to rethink where that encoding is done but I guess this is fine for now.

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 82 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5OQQPlVkZD6J1Vrs8)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L82)):</sup>
OK. You've thought about this more than I have, although one of the things I like about WebRTC signals is that they're opaque to whoever is sending them. We might be adding protocol where none is needed. But we can always change it.

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 88 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255#-Jo5PgsXlrig0fAwsIPh)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/26405ed57bb890aeeb4abdc98092ce50030f5597/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L88)):</sup>
http://en.wikipedia.org/wiki/Colossal_Cave_Adventure

Thanks, it makes me weirdly happy to have this in here :-)

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/255)

**Pull request merged**
