### PR TITLE
Remote-close test, try 2.

### PR DESCRIPTION
**Pull request by mollyling**
Rebased!

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-networking/259)

### CODE REVIEW

**Comment by mollyling** [comment]
Ref: https://github.com/uProxy/uproxy-networking/pull/226

**Comment by trevj** [comment]
Awesome, thanks. So this supercedes?:
https://github.com/uProxy/uproxy-networking/pull/226

**Comment by trevj** [comment]
:+1:

**Comment by mollyling** [comment]
Yeah, this has the same changes as 226, just not bungled up through a nasty merge.

**Pull request merged**
