### PR TITLE
Improvements related to freedom-compatible interface for socks-to-rtc

### PR DESCRIPTION
**Pull request by bemasc**
I accidentally merged the last pull request (https://github.com/uProxy/uproxy-networking/pull/170) before all the comments were in, so this one will have to serve as a continuation.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-networking/171)

### CODE REVIEW

**Comment by bemasc** [comment]
@trevj, @willscott, @iislucas, @ryscheng, this is the continuation of https://github.com/uProxy/uproxy-networking/pull/170, on which you were cc'd or had commented.

**Comment by willscott** [comment]
:+1: from me, but wait for consensus from @iislucas

**Comment by iislucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/171)

Reviewed files:
- src/socks-to-rtc/socks-to-rtc.d.ts @ r1
- src/socks-to-rtc/socks-to-rtc.ts @ r1

---

LGTM (Playing with https://reviewable.io/ to write this review) :+1:

---

**Comment by willscott** [comment]
@iislucas - I can't tell: was your only comment a ':+1:', or are there other comments made that I can't see?

**Comment by bemasc** [comment]
@iislucas, do you think I should also wait to hear from trevj@?

**Comment by iislucas** [comment]
Yes, that's my only comment! (This pull request is very minimal: it is
basically a couple of comment fixes and a type-fix. It doesn't need to be
reviewed more deeply - although the original should be looked at by Trevor
as he's the uproxy-networking owner).

On Sun, Dec 28, 2014 at 11:46 AM, Will notifications@github.com wrote:

> @iislucas https://github.com/iislucas - I can't tell: was your only
> comment a '[image: :+1:]', or are there other comments made that I can't
> see?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uProxy/uproxy-networking/pull/171#issuecomment-68205010
> .

## 

Lucas Dixon | Google Ideas

**Pull request merged**
