### PR TITLE
Implement load tests

### PR DESCRIPTION
**Pull request by bemasc**
The tests all pass in normal mode, and all fail for CHURN.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-networking/230)

### CODE REVIEW

**Comment by bemasc** [comment]
Lucas, I assigned this to you because I thought I remembered you saying that you were looking into some load tests.  I wrote these a while ago, but finally got around to porting them to the require branch and polishing them up for submission.

**Comment by iislucas** [comment]
Great to see these tests arrive in requirify, thanks for doing this! They look a lot like benchmarking tests. I think it might be nice to have them instrumented and output the results. This might be a really easy way to get regular benchmark results, and it's kind of nice in that it's all in JS land. Although that's a problem too as it obscures the possible places that are causing slow-down (e.g. we don't test to a common bit of code like nc).

---

Reviewed files:
- Gruntfile.coffee @ r1
- src/integration-tests/socks-echo/base-spec.core-env.ts @ r1
- src/integration-tests/socks-echo/freedom-module.json @ r1
- src/integration-tests/socks-echo/freedom-module.ts @ r2
- src/integration-tests/socks-echo/proxy-integration-test.ts @ r1, r2
- src/integration-tests/socks-echo/proxy-integration-test.types.ts @ r1
- src/integration-tests/socks-echo/slow.core-env.spec.ts @ r1

---

<sup>**[src/integration-tests/socks-echo/base-spec.core-env.ts, line 161 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnSv83LAG1JCSFUuCQ)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/base-spec.core-env.ts#L161)):</sup>
This type occurs in a couple places, consider naming it and moving it to the types file.

---

<sup>**[src/integration-tests/socks-echo/proxy-integration-test.types.ts, line 3 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-Jmnd5OP86MPWF0-LfuB)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/proxy-integration-test.types.ts#L3)):</sup>
Lets add a comment that says that the returned string is a connectionId, i.e. it can be passed to the methods below. 

---

<sup>**[src/integration-tests/socks-echo/proxy-integration-test.types.ts, line 4 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnTffrlDkvq3z3V7cP)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/proxy-integration-test.types.ts#L4)):</sup>
Briefly document what setRepeat does in a comment here. 

---

<sup>**[src/integration-tests/socks-echo/proxy-integration-test.types.ts, line 8 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmneThhi9J4nC4vC5H3)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/proxy-integration-test.types.ts#L8)):</sup>
Why not just have the pong value be the return argument of the ping function? and then no class abstraction is needed? 

---

<sup>**[src/integration-tests/socks-echo/slow.core-env.spec.ts, line 13 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnQWKme-lp2ZY34DgM)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/slow.core-env.spec.ts#L13)):</sup>
This is not a getter; it creates a new module. Maybe better to call it `createTestModule` ?

---

<sup>**[src/integration-tests/socks-echo/slow.core-env.spec.ts, line 54 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnSmAze2LNzFTYOZgJ)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/slow.core-env.spec.ts#L54)):</sup>
`pong:{connectionId:string; response:string;}` ?

---

<sup>**[src/integration-tests/socks-echo/slow.core-env.spec.ts, line 56 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnRPDxXMOUXR7U6upD)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/slow.core-env.spec.ts#L56)):</sup>
This selection thing is probably not needed if your ping returns a promise with the pong content... ?

---

<sup>**[src/integration-tests/socks-echo/slow.core-env.spec.ts, line 60 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnfDslpVZRAe6C2VCA)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/slow.core-env.spec.ts#L60)):</sup>
Why not just use the returned ArrayBuffer size and avoid the string conversion? 

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230)

**Comment by bemasc** [comment]
<sup>**[src/integration-tests/socks-echo/proxy-integration-test.types.ts, line 8 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmneThhi9J4nC4vC5H3)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/proxy-integration-test.types.ts#L8)):</sup>
The `'pong'` event is needed by the pre-existing tests that contact uproxy.org.  We can't use a Promise in these tests, because this class doesn't know when the transfer has completed.

To be clear, the reason for the new fake `on` method is that I didn't want to keep using the `any` type, like base-spec.core-env.spec.ts was doing for tests that use `'pong'`.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230)

**Comment by bemasc** [comment]
<sup>**[src/integration-tests/socks-echo/base-spec.core-env.ts, line 163 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnSv83LAG1JCSFUuCQ)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/base-spec.core-env.ts#L163)):</sup>
Done.

---

<sup>**[src/integration-tests/socks-echo/proxy-integration-test.types.ts, line 9 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-Jmnd5OP86MPWF0-LfuB)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/proxy-integration-test.types.ts#L9)):</sup>
Done.

---

<sup>**[src/integration-tests/socks-echo/proxy-integration-test.types.ts, line 11 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnTffrlDkvq3z3V7cP)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/proxy-integration-test.types.ts#L11)):</sup>
Done.

---

<sup>**[src/integration-tests/socks-echo/slow.core-env.spec.ts, line 13 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnQWKme-lp2ZY34DgM)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/slow.core-env.spec.ts#L13)):</sup>
Done.

---

<sup>**[src/integration-tests/socks-echo/slow.core-env.spec.ts, line 54 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnSmAze2LNzFTYOZgJ)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/slow.core-env.spec.ts#L54)):</sup>
Done.

---

<sup>**[src/integration-tests/socks-echo/slow.core-env.spec.ts, line 60 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnRPDxXMOUXR7U6upD)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/slow.core-env.spec.ts#L60)):</sup>
The "pong" actually represents all received data, which might not be for this connection in the multiple-connection tests.  I've renamed it to avoid the ping-pong metaphor, which doesn't fit.

---

<sup>**[src/integration-tests/socks-echo/slow.core-env.spec.ts, line 60 [r2]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230#-JmnfDslpVZRAe6C2VCA)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/bad6f2753fc885d0b5ac5d9584d38e149b5ada52/src/integration-tests/socks-echo/slow.core-env.spec.ts#L60)):</sup>
Done.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/230)

**Comment by bemasc** [comment]
I've responded to all the comments ... but the dev-requireify branch is dead, so I'm closing this and reopening with the new target.

**Pull request closed without merging**
