### PR TITLE
Requireify of uproxy-networking

### PR DESCRIPTION
**Pull request by iislucas**
Placeholder to start reviewing requireify of uproxy-networking.

Summary of changes:
- `.gitignore` sorted.
- Created and using a `./setup.sh` script in the style of uproxy-lib. 
- Moved test running code out of npm `package.json` and into the shippable/travis file
- Update & sorted package dependency versions
- Fixed/renamed freedom manifests to `freedom-module.json`
- Rabbit and FTE are temporarily disabled while we figure out how to make them load (the problem is that emscripten introduces some unused lines with `require` statements, but browserify doesn't understand the lines are never used; working with @kpdyer on fixes for this)
- Added .ts interface file for `churn-pipe` and separated class from freedom module. 

TESTED: 
- grunt test
- grunt integration
  - Note: currently these test leave the chrome app open.
- Manually simple apps

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-networking/225)

### CODE REVIEW

**Comment by trevj** [comment]
OK. By and large, I'm assuming you followed the same patterns as in `uproxy-lib` so I configured my difftool to ignore leading whitespace changes and focused on the `Gruntfile` and a few other key files.

The only other suggestion or comment I'd have is that I think `integration` was a better name than `integration-tests`.

---

---

<sup>**[Gruntfile.coffee, line 8 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFhOC0tY0SAXD-lxyk)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/Gruntfile.coffee#L8)):</sup>
So `uproxy-lib`'s default target is just `base` -- which I kinda prefer. Any reason you made it different here?

---

<sup>**[Gruntfile.coffee, line 180 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFhezjCH4jh7VXmgeY)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/Gruntfile.coffee#L180)):</sup>
remove commented lines!

---

<sup>**[Gruntfile.coffee, line 203 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFhiINfdTDUq95FqJv)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/Gruntfile.coffee#L203)):</sup>
indentation is weird (should be 2, not 4)

---

<sup>**[package.json, line 23 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFgwRMJbNNk7eDVyEb)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/package.json#L23)):</sup>
No need to conduct an extensive pruning of this file but I see you've removed a bunch of stuff in the Gruntfile related to Android - which is great, BTW, it hasn't received any attention for a _long_ time - and some of the items listed here were added purely to support Android...`cca`, in particular, is a huge package and it would be very nice to remove it now.

---

<sup>**[setup.sh, line 49 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFfj2-gQOVWRtlhFFq)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/setup.sh#L49)):</sup>
looks like you can remove this now :-)

---

<sup>**[src/churn/churn.ts, line 379 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFn7u-zTQ_JwsuYPSr)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/churn/churn.ts#L379)):</sup>
I'm curious where the static constructor went?

---

<sup>**[src/rtc-to-net/rtc-to-net.ts, line 243 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFj14okLvhSxyGeG8T)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/rtc-to-net/rtc-to-net.ts#L243)):</sup>
from line 391:

``` js
      // DataChannel.close() returns void, implying that the shutdown is
      // effectively immediate.  However, we wrap it in a promise to ensure
      // that any exception is sent to the Promise.catch, rather than
      // propagating synchronously up the stack.
```

---

<sup>**[src/simple-socks/freedom-module.ts, line 21 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFjofIhMiIGq07THMi)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/simple-socks/freedom-module.ts#L21)):</sup>
Let's keep it at `I`, the proxy is barely usable in DEBUG.

---

<sup>**[src/simple-socks/freedom-module.ts, line 43 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFmsZHpZ8NCi3ju3c8)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/simple-socks/freedom-module.ts#L43)):</sup>
I don't think we're quite ready to enable obfuscation yet :-)

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225)

**Comment by iislucas** [comment]
Reviewed files:
- .bowerrc @ r1
- .gitignore @ r1
- .shippable.yml @ r1
- .travis.yml @ r1
- editor_support/sublime_text/uproxy-networking.sublime-project @ r1
- Gruntfile.coffee @ r1
- package.json @ r1
- setup.sh @ r1
- src/benchmark/agent.d.ts @ r1
- src/benchmark/benchmark.ts @ r1
- src/churn-pipe/churn-pipe.d.ts @ r1
- src/churn-pipe/churn-pipe.ts @ r1
- src/churn-pipe/freedom-module.interface.ts @ r1
- src/churn-pipe/freedom-module.json @ r1
- src/churn-pipe/freedom-module.ts @ r1
- src/churn-pipe/freedom.json @ r1
- src/churn/churn.d.ts @ r1
- src/churn/churn.spec.ts @ r1
- src/churn/churn.ts @ r1
- src/churn/churn.types.ts @ r1
- src/churn/mocks.js @ r1
- src/echo/freedom-module.json @ r1
- src/echo/freedom-module.ts @ r1
- src/echo/tcp-echo-server.ts @ r1
- src/integration-tests/socks-echo/base-spec.core-env.ts @ r1
- src/integration-tests/socks-echo/churn.core-env.spec.ts @ r1
- src/integration-tests/socks-echo/freedom-module.json @ r1
- src/integration-tests/socks-echo/freedom-module.ts @ r1
- src/integration-tests/socks-echo/nochurn.core-env.spec.ts @ r1
- src/integration-tests/socks-echo/proxy-integration-test.types.ts @ r1
- src/integration-tests/socks-echo/slow.core-env.spec.ts @ r1
- src/integration-tests/tcp/freedom-module.json @ r1
- src/integration-tests/tcp/freedom-module.ts @ r1
- src/integration/socks-echo/integration.json @ r1
- src/integration/socks-echo/integration.ts @ r1
- src/integration/socks-echo/socks-echo.churn_integration.spec.ts @ r1
- src/integration/socks-echo/socks-echo.integration.spec.ts @ r1
- src/integration/socks-echo/socks-echo.integration.spec_base.ts @ r1
- src/integration/socks-echo/socks-echo.slow_integration.spec.ts @ r1

---

<sup>**[Gruntfile.coffee, line 8 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFhOC0tY0SAXD-lxyk)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/Gruntfile.coffee#L8)):</sup>
I agree; now just base

---

<sup>**[Gruntfile.coffee, line 180 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFhezjCH4jh7VXmgeY)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/Gruntfile.coffee#L180)):</sup>
Done.

---

<sup>**[Gruntfile.coffee, line 203 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFhiINfdTDUq95FqJv)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/Gruntfile.coffee#L203)):</sup>
Done.

---

<sup>**[setup.sh, line 49 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFfj2-gQOVWRtlhFFq)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/setup.sh#L49)):</sup>
Done.

---

<sup>**[src/churn/churn.ts, line 379 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFn7u-zTQ_JwsuYPSr)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/churn/churn.ts#L379)):</sup>
Good question! So I think there were two static constructors, but the one here was just calling the class constructor with the same arguments; so I didn't see any benefit for it in this case. 

---

<sup>**[src/rtc-to-net/rtc-to-net.ts, line 243 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFj14okLvhSxyGeG8T)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/rtc-to-net/rtc-to-net.ts#L243)):</sup>
If that's what is going on, then we don't need to return a promise at all, right? just call `this.peerConnection_.close();` comment updated. 

---

<sup>**[src/simple-socks/freedom-module.ts, line 21 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFjofIhMiIGq07THMi)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/simple-socks/freedom-module.ts#L21)):</sup>
Yes.... now I think about it, it's probably better set at the top-level consumer rather than within the module. I've set it to info at the freedom level in the same app. 

---

<sup>**[src/simple-socks/freedom-module.ts, line 43 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFmsZHpZ8NCi3ju3c8)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/simple-socks/freedom-module.ts#L43)):</sup>
I agree, turned off. 

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225)

**Comment by iislucas** [comment]
<sup>**[src/simple-socks/freedom-module.ts, line 21 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225#-JmFjofIhMiIGq07THMi)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/733ce52c9823175250bd54f5bc16794411ee086e/src/simple-socks/freedom-module.ts#L21)):</sup>
After discussion, I agree this is probably the best place to set this as the core-environment freedom object doesn't let you interact with the logging provider. 

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225)

**Comment by trevj** [comment]
:+1:

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/225)

**Pull request merged**
