### PR TITLE
Cordova tasks

### PR DESCRIPTION
**Pull request by ryscheng**
Update to freedom 0.4.12 (includes fixes to work in Cordova)
Adding cordova tasks (grunt cca)

### CODE REVIEW

**Comment by iislucas** [comment]
oops, I missed this in the busyness of the world. Probably good to rebase, and make sure it still works. :) 

Please include how you test it in the comment for the pull request. And after that :+1: 

nice!

**Comment by iislucas** [comment]
:+1:  again :)

**Comment by ryscheng** [comment]
7/22 - verified works, includes changes from HEAD on master.
Both the SOCKS5 proxy and the echo server now work.

**Comment by iislucas** [comment]
:+1: :+1:  Merge away.

**Pull request merged**
