### PR TITLE
Make (TCP) integration tests run.

### PR DESCRIPTION
**Pull request by bemasc**
[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-networking/211)

### CODE REVIEW

**Comment by iislucas** [comment]
:+1:

**Comment by bemasc** [comment]
I'm not going to merge this one automatically because of my accidental reversion of some commits in iislucas-requireify.  @iislucas, please merge once we've recovered from that accident, or let me know if I should rebase this branch.

**Comment by iislucas** [comment]
TODO: leverage the nice features of the `files` section: 
https://github.com/willscott/grunt-jasmine-chromeapp/issues/15

to make the layout in the integration tests like the sample apps.

**Comment by iislucas** [comment]
Merged into iislucas-requireify manually.

**Pull request closed without merging**
