### PR TITLE
Update to new version of uproxy-lib

### PR DESCRIPTION
**Pull request by jpevarnek**
[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-networking/232)

### CODE REVIEW

**Comment by bemasc** [comment]
:+1:

**Comment by trevj** [comment]
Many thanks for helping to push this through!

A few comments, none of them should be tricky to address. Then, :+1:.

---

<sup>**[src/echo/freedom-module.ts, line 14 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsPQBg30wkOGKGZSH4)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/echo/freedom-module.ts#L14)):</sup>
indentation: 4 spaces

---

<sup>**[src/integration-tests/socks-echo/freedom-module.ts, line 10 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsPWnI5KQCUfk_y4xY)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/integration-tests/socks-echo/freedom-module.ts#L10)):</sup>
indentation

---

<sup>**[src/integration-tests/tcp/freedom-module.ts, line 12 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsPZBmVAY9neBvjnEC)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/integration-tests/tcp/freedom-module.ts#L12)):</sup>
indentation

---

<sup>**[src/samples/copypaste-churn-chat-chromeapp/freedom-module.ts, line 12 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsP_YBhosEfUsdwerB)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/samples/copypaste-churn-chat-chromeapp/freedom-module.ts#L12)):</sup>
indentation

---

<sup>**[src/samples/copypaste-socks-chromeapp/freedom-module.ts, line 20 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsPaz3IbXlDIuyYDZR)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/samples/copypaste-socks-chromeapp/freedom-module.ts#L20)):</sup>
indentation

---

<sup>**[src/samples/simple-churn-chat-chromeapp/freedom-module.ts, line 13 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsPhWGSqgKP54mT1M_)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/samples/simple-churn-chat-chromeapp/freedom-module.ts#L13)):</sup>
Would you mind copying in an example of how to configure the logger here, too? I think all the other sample apps have it.

---

<sup>**[src/samples/simple-churn-chat-chromeapp/freedom-module.ts, line 13 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsQoJAdU01XFP51ctf)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/samples/simple-churn-chat-chromeapp/freedom-module.ts#L13)):</sup>
Did you forget to add `logginglistener` to this module's JSON definition?

---

<sup>**[src/samples/simple-turn-chromeapp/freedom-module.ts, line 14 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsPmhmrH60SBozfH8-)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/samples/simple-turn-chromeapp/freedom-module.ts#L14)):</sup>
indentation

---

<sup>**[src/simple-socks/freedom-module.ts, line 17 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsQG6NWeh1xFd71EJw)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/simple-socks/freedom-module.ts#L17)):</sup>
I think you can now quite justifiably update this comment :-)

(likewise in copypaste socks -- let's just make this section identical in both)

---

<sup>**[src/simple-socks/freedom-module.ts, line 18 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsQ_zSYR2uNNHW6Y-9)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/simple-socks/freedom-module.ts#L18)):</sup>
This is by the most heavily used sample app. Can you add a call to configure the default level, too?

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232)

**Comment by trevj** [comment]
Could you also update the pull request's description to mention logginglistener? Thanks.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232)

**Comment by bemasc** [comment]
<sup>**[src/churn-pipe/freedom-module.json, line 64 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsiIINM9m4QjptPBdO)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/churn-pipe/freedom-module.json#L64)):</sup>
Try running jasmine_chromeapp:socksEchoChurn ... this doesn't seem to be working

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232)

**Comment by jpevarnek** [comment]
Going to push in a few minutes.

---

<sup>**[src/churn-pipe/freedom-module.json, line 64 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsiIINM9m4QjptPBdO)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/churn-pipe/freedom-module.json#L64)):</sup>
It looks like merging dev in fixes that.

---

<sup>**[src/samples/simple-churn-chat-chromeapp/freedom-module.ts, line 13 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsPhWGSqgKP54mT1M_)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/samples/simple-churn-chat-chromeapp/freedom-module.ts#L13)):</sup>
Done.

---

<sup>**[src/samples/simple-churn-chat-chromeapp/freedom-module.ts, line 13 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsQoJAdU01XFP51ctf)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/samples/simple-churn-chat-chromeapp/freedom-module.ts#L13)):</sup>
Done.

---

<sup>**[src/simple-socks/freedom-module.ts, line 17 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsQG6NWeh1xFd71EJw)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/simple-socks/freedom-module.ts#L17)):</sup>
Done.

---

<sup>**[src/simple-socks/freedom-module.ts, line 18 [r1]](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232#-JmsQ_zSYR2uNNHW6Y-9)** ([raw file](https://github.com/uproxy/uproxy-networking/blob/ddbbf63b3625dd53bd68ee2c2c791df7e214272e/src/simple-socks/freedom-module.ts#L18)):</sup>
Done.

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232)

**Comment by trevj** [comment]
:+1:

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-networking/232)

**Pull request merged**
